meta_product_name: "Kaizo Studio"
meta_title: "Kaizo Studio | Agence d'architecture intérieure à Bourg-la-Reine"
meta_description: "Kaizo Studio est une agence d'architecture intérieure qui vous accompagne dans votre projet de rénovation, de la conception à la réalisation."
meta_image: "cover.png"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@trandgthanh"              # indispensable pour les Twitter Cards
